Dictionary 1.1
Silumgaaar/Dictionary pull request #6
Opened 2022-03-09 20:59 UTC by Silumgaaar

2022-03-09 21:05 UTC, NikolayKlyatishev reviewed
Тип поля

2022-03-09 21:05 UTC, NikolayKlyatishev commented on src/main/dictionarywork/Dictionary.java
> +    private HashMap<String,String> dictionary = new HashMap<>();
Не стоит использовать в качестве полей типы реализации. Используем интерфейсы.

2022-03-09 21:30 UTC, Silumgaaar commented on src/main/dictionarywork/Dictionary.java
> +    private HashMap<String,String> dictionary = new HashMap<>();
Заменил HashMap на Map

2022-03-09 21:37 UTC, NikolayKlyatishev requested changes
Не стоит использовать тип реализации HashMap так же и в качестве возвращаемого типа метода.

2022-03-09 23:29 UTC, NikolayKlyatishev requested changes
Подправить и думаю иожно бубет мержить изменения.

2022-03-09 23:29 UTC, NikolayKlyatishev commented on src/main/dictionarywork/DictionaryManager.java
> +    boolean newDictionary(String name);
Подумай над тем, чтобы убрать инициализацию из интерфейса. Думаю стоит просто создать новую реализацию для обработки файла с именами, регулярками словарей.

2022-03-09 23:29 UTC, NikolayKlyatishev commented on src/main/directory/DirectoryWork.java
> +public interface DirectoryWork {
Этот интерфейс очень напоминает интерфейс Dictionary. Зачем их 2?

2022-03-09 23:29 UTC, NikolayKlyatishev commented on src/main/view/commands/Back.java
>      public void execute(DictionaryManager dictionaryManager) {
Вынести словарь в поля класса. Подумать нал тем, как сделать так, чтобы словарь был 1 для всех команд, а не для каждой свой. 
Думаю связывание объектов нудно выполнить при старте программы, а не передавать сюда экземпляр, потому как во всех методах, откуда мы вызываем этот метод должен быть объект менеджера.

2022-03-09 23:29 UTC, NikolayKlyatishev commented on src/main/view/commands/Back.java
> +        return infoCommands;
Думаю тут достаточно вернуть BACK. Поле лишнее т.к. не задумано его изменение в принципе.

2022-03-09 23:29 UTC, NikolayKlyatishev commented on src/main/view/commands/Command.java
> +public interface Command {
Стоит переименовать. Обычно интерфейсы принято называть деепричастиями. Например - Flyable

2022-03-09 23:29 UTC, NikolayKlyatishev commented on src/main/view/commands/Command.java
> +    main.view.Commands getInfo();
Поправь тип пожалуйста. Вероятно при рефакторинге имя энума и интерфейса совпали

2022-03-09 23:29 UTC, NikolayKlyatishev commented on src/main/view/commands/Search.java
> +        Scanner choice = new Scanner(System.in);
Оставь имя переменной scanner. Это устоявшееся имя сканнера)

2022-03-09 23:29 UTC, NikolayKlyatishev commented on src/main/view/Commands.java
> +    public static boolean checkCommand(String command){
Этот метод не нужен. Зачем что-то проверять? Просто стратегию из мапы к ConsoleApp. Если не нашел - нет такой команды.

2022-03-09 23:29 UTC, NikolayKlyatishev commented on src/main/view/ConsoleApp.java
> +        String userChoice = "";
Зачем объявление переменной тут, если ты ее сразу же не используешь?

2022-03-09 23:29 UTC, NikolayKlyatishev commented on src/resources/DictionaryType1.txt
> +vieg-виег
Почему словарь не добавлен в .gitignore?

2022-03-10 06:33 UTC, Silumgaaar commented on src/resources/DictionaryType1.txt
> +vieg-виег
Добавил

2022-03-10 06:44 UTC, Silumgaaar commented on src/main/view/commands/Search.java
> +        Scanner choice = new Scanner(System.in);
Изменил на scanner

2022-03-10 06:48 UTC, Silumgaaar commented on src/main/view/ConsoleApp.java
> +        String userChoice = "";
Переместил

2022-03-10 06:56 UTC, Silumgaaar commented on src/main/view/commands/Command.java
> +    main.view.Commands getInfo();
Поправил, поменял имя интерфейса на Commander

2022-03-10 07:01 UTC, Silumgaaar commented on src/main/view/Commands.java
> +    public static boolean checkCommand(String command){
Убрал метод

2022-03-10 07:02 UTC, Silumgaaar commented on src/main/view/commands/Command.java
> +public interface Command {
Переименовал

2022-03-10 07:06 UTC, Silumgaaar commented on src/main/view/commands/Command.java
> +    main.view.Commands getInfo();
Поправил

2022-03-10 07:36 UTC, Silumgaaar commented on src/main/view/commands/Back.java
>      public void execute(DictionaryManager dictionaryManager) {
Вынес словарь в поле класса

2022-03-10 14:04 UTC, NikolayKlyatishev requested changes
Переменная userChoice

2022-03-10 14:04 UTC, NikolayKlyatishev commented on src/main/view/ConsoleApp.java
> +            String userChoice;
Объедини инициализацию переменной и присвоение ей значения.

2022-03-10 18:40 UTC, NikolayKlyatishev requested changes
Оставил комментарии по остальным комитам.

2022-03-10 18:40 UTC, NikolayKlyatishev commented on src/main/view/ConsoleApp.java
> +                commander = commands.get(userChoice);
Думаю 2 раза получать команду из мапы неверно)

2022-03-11 06:08 UTC, Silumgaaar commented on src/main/view/ConsoleApp.java
> +            String userChoice;
Поправил

2022-03-11 10:26 UTC, Silumgaaar commented on src/main/view/ConsoleApp.java
> +                commander = commands.get(userChoice);
Поправил

2022-03-14 23:34 UTC, NikolayKlyatishev requested changes
Финальнеые замечания

2022-03-14 23:34 UTC, NikolayKlyatishev commented on src/main/dictionarywork/DictionaryManager.java
> +    Map<String,String> getAll();
Не понятно назначение метода view() Делает то же самое, что и  getAll()?

2022-03-14 23:34 UTC, NikolayKlyatishev commented on src/main/dictionarywork/Dictionary.java
> +        newDictionary(name);
Просьба убрать из именования методов слово new. Это нарушение соглашения об именовании.

2022-03-14 23:34 UTC, NikolayKlyatishev commented on src/main/dictionarywork/Dictionary.java
>          return dictionary;
Нельзя отдавать ссылку наружу. Состояние объекта должно быть инкапсулировано внутри.

2022-03-14 23:34 UTC, NikolayKlyatishev commented on src/main/dictionarywork/Dictionary.java
> +            fileOverWrite(patch);
зачем передавать внутрь patch? Это же поле класса?

2022-03-14 23:34 UTC, NikolayKlyatishev commented on src/main/dictionarywork/Dictionary.java
>      private String patch;
Неверный смысл слова) Думаю ты имел ввиду path

2022-03-14 23:34 UTC, NikolayKlyatishev commented on src/main/dictionarywork/Dictionary.java
> +        Map<String,String> infoDictionary;
Почему отдельно инициализируешь переменную, а только потом присваиваешь значение?

2022-03-14 23:34 UTC, NikolayKlyatishev commented on src/main/structure/ConfigDictionary.java
> +    private Map<String,String> newInfoDictionary(String name) {
убрать new из имени метода. Нарушение соглашения об именовании

2022-03-14 23:34 UTC, NikolayKlyatishev commented on src/main/view/ConsoleApp.java
> +        Commander commander = commands.get("Back");
Почему ты тут достаешь по строке? Зачем вобще доставать? При изменении команды придется помнить, что нужно поменять и тут! Создай новый объект руками и используй его имя.

2022-03-15 07:49 UTC, Silumgaaar commented on src/main/dictionarywork/DictionaryManager.java
> +    Map<String,String> getAll();
поправил, убрал лишний метод

2022-03-15 07:50 UTC, Silumgaaar commented on src/main/dictionarywork/Dictionary.java
> +        newDictionary(name);
Поправил

2022-03-15 07:50 UTC, Silumgaaar commented on src/main/dictionarywork/Dictionary.java
> +        newDictionary(name);
Исправил на createDictionary

2022-03-15 07:55 UTC, Silumgaaar commented on src/main/dictionarywork/Dictionary.java
> +            fileOverWrite(patch);
Поправил

2022-03-15 07:59 UTC, Silumgaaar commented on src/main/dictionarywork/Dictionary.java
>      private String patch;
Поправил :D

2022-03-15 08:02 UTC, Silumgaaar commented on src/main/dictionarywork/Dictionary.java
> +        Map<String,String> infoDictionary;
Поправил

2022-03-15 08:05 UTC, Silumgaaar commented on src/main/structure/ConfigDictionary.java
> +    private Map<String,String> newInfoDictionary(String name) {
поправил

2022-03-15 08:18 UTC, Silumgaaar commented on src/main/dictionarywork/Dictionary.java
>          return dictionary;
Поправил

2022-03-15 08:26 UTC, Silumgaaar commented on src/main/view/ConsoleApp.java
> +        Commander commander = commands.get("Back");
поправил

2022-03-16 18:24 UTC, NikolayKlyatishev requested changes
Правки

2022-03-16 18:24 UTC, NikolayKlyatishev commented on src/main/java/org/example/dictionarywork/Dictionary.java
> +        Map<String,String> dictionary;
Изучить разницу между ссылками и объектами в java

2022-03-16 18:24 UTC, NikolayKlyatishev commented on src/main/java/org/example/view/ConsoleApp.java
> +        Commander commander = new Back(configDictionary);
Неверно. У тебя уже есть такой объект. Достань его оттуда. Нужно только подумать как.
Плюс зависимость ConsoleApp от ConfigDictionary явно лишняя.

2022-03-16 18:24 UTC, NikolayKlyatishev commented on src/main/java/org/example/view/ConsoleApp.java
> +    public void start(ConfigDictionary configDictionary){
Что тебе придется сделать, если строка команды "Exit"  поменяется?

2022-03-16 18:24 UTC, NikolayKlyatishev commented on src/main/java/org/example/view/ConsoleApp.java
> +    public void start(ConfigDictionary configDictionary){
При каждой итерации новый сканнер делать? Это лишние расходы ресурсов.

2022-03-17 20:57 UTC, Silumgaaar commented on src/main/java/org/example/view/ConsoleApp.java
> +    public void start(ConfigDictionary configDictionary){
поправил

2022-03-17 20:57 UTC, Silumgaaar commented on src/main/java/org/example/view/ConsoleApp.java
> +    public void start(ConfigDictionary configDictionary){
поправил

2022-03-18 13:58 UTC, NikolayKlyatishev requested changes
ревью

2022-03-18 13:58 UTC, NikolayKlyatishev commented on src/main/java/ru/yarkin/structure/ConfigDictionary.java
> +    DictionaryManager dictionary;
Нарушение инкапсуляции

2022-03-18 13:58 UTC, NikolayKlyatishev commented on src/main/resources/applicationContext.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Откуда этот файл в консольном приложении?

2022-03-18 13:58 UTC, NikolayKlyatishev commented on src/main/java/ru/yarkin/Main.java
> +        List<Commander> listCommand = new ArrayList<>();
Почему объявление не в месте использования?

2022-03-18 13:58 UTC, NikolayKlyatishev commented on src/main/java/ru/yarkin/view/commands/Back.java
> +        infoCommands = Commands.getCommandInfo("Back");
Почему опять по строке ищешь? При изменении enum придется вспомнить, что тут тоже надо поправить. Нарушение инкапсуляции.

2022-03-18 13:58 UTC, NikolayKlyatishev commented on src/main/java/ru/yarkin/view/commands/Back.java
> +    public Commands getInfo() {
Зачем полем делать, если используется только в 1 методе?

2022-03-18 13:58 UTC, NikolayKlyatishev commented on src/main/java/ru/yarkin/view/commands/View.java
> +            System.out.println(entry);
Как оптимизировать метод? Ресурс вывода в консоль достаточно дорогой.

2022-03-18 13:58 UTC, NikolayKlyatishev commented on src/main/java/ru/yarkin/dictionarywork/Dictionary.java
> +            System.out.println("File not found");
Почему мы отсюда клиенту выкидываем ошибку в лицо? Разве для этого слой работы с данными нужен? И почему file not found только?

2022-03-20 14:01 UTC, Silumgaaar commented on src/main/resources/applicationContext.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Убрал

2022-03-20 15:30 UTC, Silumgaaar commented on src/main/java/ru/yarkin/structure/ConfigDictionary.java
> +    DictionaryManager dictionary;
Поправил

2022-03-20 15:31 UTC, Silumgaaar commented on src/main/java/ru/yarkin/Main.java
> +        List<Commander> listCommand = new ArrayList<>();
поправил

2022-03-20 15:37 UTC, Silumgaaar commented on src/main/java/ru/yarkin/view/commands/Back.java
> +        infoCommands = Commands.getCommandInfo("Back");
Исправил

2022-03-20 15:43 UTC, Silumgaaar commented on src/main/java/ru/yarkin/view/commands/View.java
> +            System.out.println(entry);
Исправил

2022-03-20 15:57 UTC, Silumgaaar commented on src/main/java/ru/yarkin/view/commands/Back.java
> +    public Commands getInfo() {
Мы в ConsoleApp заполняем HashMap ключами с помощью этого метода. Чтобы потом доставать команды по ключу

2022-03-22 20:37 UTC, NikolayKlyatishev commented on src/main/java/ru/yarkin/structure/ConfigDictionary.java
> +        String[] info =  directory.getAll().get(name).split(DELIMITER);
Мне не нравится реализация, при которой класс конфига содержит в себе разделитель, который вроде вообще в слое данных должен быть.

2022-03-22 20:45 UTC, NikolayKlyatishev requested changes

2022-03-22 20:45 UTC, NikolayKlyatishev commented on src/main/java/ru/yarkin/structure/ConfigDictionary.java
> +    public Map<String,String> getInfoDictionary(String name){
Точно тут нужен этот метод?

2022-03-22 20:45 UTC, NikolayKlyatishev commented on src/main/java/ru/yarkin/structure/ConfigDictionary.java
> +public class ConfigDictionary{
Для чего нужно было создавать этот класс? Какое его предназначение?

2022-03-24 12:50 UTC, Silumgaaar commented on src/main/java/ru/yarkin/dictionarywork/Dictionary.java
> +            System.out.println("File not found");
Поправил

2022-03-24 13:40 UTC, Silumgaaar commented on src/main/java/org/example/dictionarywork/Dictionary.java
> +        Map<String,String> dictionary;
Сделано

2022-03-25 06:03 UTC, Silumgaaar commented on src/main/java/ru/yarkin/structure/ConfigDictionary.java
> +        String[] info =  directory.getAll().get(name).split(DELIMITER);
поправил

2022-03-25 06:04 UTC, Silumgaaar commented on src/main/java/ru/yarkin/structure/ConfigDictionary.java
> +    public Map<String,String> getInfoDictionary(String name){
переделал

2022-03-25 06:04 UTC, Silumgaaar commented on src/main/java/ru/yarkin/structure/ConfigDictionary.java
> +public class ConfigDictionary{
В нем хранится директория и словарь с которым мы работаем

2022-05-31 07:01 UTC, closed without merging